accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name="register"), # register
    path('login/', views.login_view, name="login"), # login
]

medi_app/urls.py
from django.urls import path
from . import views
app_name = 'medi_app'

urlpatterns = [
    path('', views.home, name="home"), # home url
    path('about/', views.about, name="about"), # about url
    path('appointment/', views.appointment, name="appointment"), # appointment url
    path('show_appointments/', views.retrieve_appointments, name="show_appointments"), # url to show the appoinments
    path('delete/<int:id>', views.delete_appointment, name="delete_appointment"), # delete
    path('edit/<int:appointment_id>', views.update_appointment, name="update_appointment"),

    path('pay/', views.pay, name='pay'), # view the payment form
    path('stk/', views.stk, name='stk'), # send the stk push prompt
    path('token/', views.token, name='token'), # generate the token for that particular transaction
]

proj_bootstrap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # urls for my apps
    path('', include('medi_app.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

medi_app/models.py
from django.db import models

# Create your models here.

class Appointment(models.Model):
    """ Appointment table """
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=10)
    date = models.DateField()
    department = models.CharField(max_length=10)
    doctor = models.CharField(max_length=10)
    message = models.TextField()
    
    # To return the values in human readable format

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login


# Create your views here.
# Register
def register(request):
    """ Show the registration form """
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        # Check the password
        if password == confirm_password:
            try:
                user = User.objects.create_user(username=username, password=password)
                user.save()
                
                # Display a message
                messages.success(request, "Account created successfully")
                return redirect('accounts:login')
            except:
                # Display a message if the above fails
                messages.error(request, "Username already exist")
        else:
            # Display a message saying passwords don't match
            messages.error(request, "Passwords do not match")
        
    return render(request, 'accounts/register.html')


# Login
def login_view(request):
    """ Login view """
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        # Check if the user exists
        if user is not None:
            login(request, user)
            messages.success(request, "You are now logged in!")
            return redirect("medi_app:home")
        else:
            messages.error(request, "Invalid login credentials")

    return render(request, 'accounts/login.html')

medi_app/views.py
import requests
import json

from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from medi_app.credentials import LipanaMpesaPpassword, MpesaAccessToken
# Import the model
from .models import Appointment
# Import the login_required
from django.contrib.auth.decorators import login_required


@login_required
# Create your views here.
def home(request):
    """ Display the home page """
    return render(request, 'index.html')

def about(request):
    """ Display the about page """
    return render(request, 'about.html')

@login_required(login_url='accounts:login')
def appointment(request):
    """ Appointment booking """
    # Check if its a post method
    if request.method == 'POST':
        # Create variable to pick the input fields
        appointments = Appointment(
            # list the input fields here
            name = request.POST['name'],
            email = request.POST['email'],
            phone = request.POST['phone'],
            date = request.POST['date'],
            department = request.POST['department'],
            doctor = request.POST['doctor'],
            message = request.POST['message'],
        )
        # save the variable
        appointments.save()
        # redirect to a page
        return redirect('medi_app:home')
    else:
        return render(request, 'appointment.html')


# Retrieve all appointments
def retrieve_appointments(request):
    """ Retrieve/fetch all appointments """
    # Create a variable to store these appointments
    appointments = Appointment.objects.all()
    context = {
        'appointments':appointments
        }
    return render(request, 'show_appointments.html', context)


# Delete
def delete_appointment(request, id):
    """ Deleting """
    appointment = Appointment.objects.get(id=id) # fetch the particular appointment by its ID
    appointment.delete() # actual action of deleting
    return redirect("medi_app:show_appointments") # just remain on the same page


# Update
def update_appointment(request, appointment_id):
    """ Update the appointments """
    appointment = get_object_or_404(Appointment, id=appointment_id)
    # Put the condition for the form to update
    if request.method == 'POST':
        appointment.name = request.POST.get('name')
        appointment.email = request.POST.get('email')
        appointment.phone = request.POST.get('phone')
        appointment.date = request.POST.get('date')
        appointment.doctor = request.POST.get('doctor')
        appointment.department = request.POST.get('department')
        appointment.message = request.POST.get('message')
        # Once you click on the update button
        appointment.save()

        return redirect("medi_app:show_appointments")
    
    context = {'appointment': appointment}
    return render(request, "update_appointment.html", context)




# Adding the mpesa functions

#Display the payment form
def pay(request):
   """ Renders the form to pay """
   return render(request, 'pay.html')


# Generate the ID of the transaction
def token(request):
    """ Generates the ID of the transaction """
    consumer_key = 'qvQFfRUmIIMKcLutXyGEdAbkKtYN7RzIjVKiMz8Ma94qQt4q'
    consumer_secret = 'HRSVAAGk1AEG4ZATjzWmqYSTpGluFG6Erf8gRab85NEepozIGSmTPmR6k2Cu9Ivr'
    api_URL = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'

    r = requests.get(api_URL, auth=HTTPBasicAuth(
        consumer_key, consumer_secret))
    mpesa_access_token = json.loads(r.text)
    validated_mpesa_access_token = mpesa_access_token["access_token"]

    return render(request, 'token.html', {"token":validated_mpesa_access_token})


# Send the stk push
def stk(request):
    """ Sends the stk push prompt """
    if request.method =="POST":
        phone = request.POST['phone']
        amount = request.POST['amount']
        access_token = MpesaAccessToken.validated_mpesa_access_token
        api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
        headers = {"Authorization": "Bearer %s" % access_token}
        request = {
            "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
            "Password": LipanaMpesaPpassword.decode_password,
            "Timestamp": LipanaMpesaPpassword.lipa_time,
            "TransactionType": "CustomerPayBillOnline",
            "Amount": amount,
            "PartyA": phone,
            "PartyB": LipanaMpesaPpassword.Business_short_code,
            "PhoneNumber": phone,
            "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
            "AccountReference": "eMobilis",
            "TransactionDesc": "Web Development Charges"
        }
        response = requests.post(api_url, json=request, headers=headers)
        return HttpResponse("Success")

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} About {% endblock %}

{% block content %}
    <!-- About Section -->
    <section id="about" class="about section">

        <div class="container">
  
          <div class="row gy-4 gx-5">
  
            <div class="col-lg-6 position-relative align-self-start" data-aos="fade-up" data-aos-delay="200">
              <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="">
              <a href="https://www.youtube.com/watch?v=Y7f98aduVJ8" class="glightbox pulsating-play-btn"></a>
            </div>
  
            <div class="col-lg-6 content" data-aos="fade-up" data-aos-delay="100">
              <h3>About Us</h3>
              <p>
                Dolor iure expedita id fuga asperiores qui sunt consequatur minima. Quidem voluptas deleniti. Sit quia molestiae quia quas qui magnam itaque veritatis dolores. Corrupti totam ut eius incidunt reiciendis veritatis asperiores placeat.
              </p>
              <ul>
                <li>
                  <i class="fa-solid fa-vial-circle-check"></i>
                  <div>
                    <h5>Ullamco laboris nisi ut aliquip consequat</h5>
                    <p>Magni facilis facilis repellendus cum excepturi quaerat praesentium libre trade</p>
                  </div>
                </li>
                <li>
                  <i class="fa-solid fa-pump-medical"></i>
                  <div>
                    <h5>Magnam soluta odio exercitationem reprehenderi</h5>
                    <p>Quo totam dolorum at pariatur aut distinctio dolorum laudantium illo direna pasata redi</p>
                  </div>
                </li>
                <li>
                  <i class="fa-solid fa-heart-circle-xmark"></i>
                  <div>
                    <h5>Voluptatem et qui exercitationem</h5>
                    <p>Et velit et eos maiores est tempora et quos dolorem autem tempora incidunt maxime veniam</p>
                  </div>
                </li>
              </ul>
            </div>
  
          </div>
  
        </div>
  
      </section><!-- /About Section -->
  
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login {% endblock %}

{% block content %}

{% if messages %}
<ul>
  {% for message in messages %} 
  <li style="color: {% if message.tags == 'error' %}red{% else %}green{% endif %};">
    {{ message }}
  </li>
  {% endfor %}
</ul>

{% endif %}

<div class="wrapper fadeInDown">
  <div id="formContent">
    <!-- Tabs Titles -->
     <p>Login</p>
    <!-- Login Form -->
    <form method="post">
        {% csrf_token %}
      <input type="text" id="login" class="fadeIn second" name="username" placeholder="Username">
      <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password">
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>

    <!-- Remind Passowrd -->
    <div id="formFooter">
      <a class="underlineHover" href="#">Forgot Password?</a>
    </div>

  </div>
</div>

{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Register {% endblock %}

{% block content %}

{% if messages %}
<ul>
  {% for message in messages %} 
  <li style="color: {% if message.tags == 'error' %}red{% else %}green{% endif %};">
    {{ message }}
  </li>
  {% endfor %}
</ul>

{% endif %}

<div class="container">

<div class="card bg-light">
<article class="card-body mx-auto" style="max-width: 400px;">
	<h4 class="card-title mt-3 text-center">Create Account</h4>
	<p class="text-center">Get started with your free account</p>
	<p>
		<a href="" class="btn btn-block btn-twitter"> <i class="fab fa-twitter"></i>   Login via Twitter</a>
		<a href="" class="btn btn-block btn-facebook"> <i class="fab fa-facebook-f"></i>   Login via facebook</a>
	</p>
	<p class="divider-text">
        <span class="bg-light">OR</span>
    </p>
	<form method="post">
		{% csrf_token %}
	<div class="form-group input-group">
		<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
		</div>
        <input name="username" class="form-control" placeholder="Username" type="text">
	</div>
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		</div>
        <input name="password" class="form-control" placeholder="Create password" type="password">
    </div> <!-- form-group// -->
    <div class="form-group input-group">
    	<div class="input-group-prepend">
		    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
		</div>
        <input name="confirm_password" class="form-control" placeholder="Confirm password" type="password">
    </div> <!-- form-group// -->                                      
    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-block"> Create Account  </button>
    </div> <!-- form-group// -->      
    <p class="text-center">Have an account? <a href="">Log In</a> </p>                                                                 
</form>
</article>
</div> <!-- card.// -->

</div> 
<!--container end.//-->
{% endblock %}

templates/appointment.html
{% extends 'base.html' %}
{% block title %} Appointments {% endblock %}

{% block content %}
    <!-- Appointment Section -->
    <section id="appointment" class="appointment section">

        <!-- Section Title -->
        <div class="container section-title" data-aos="fade-up">
          <h2>Appointment</h2>
          <p>Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
        </div><!-- End Section Title -->
  
        <div class="container" data-aos="fade-up" data-aos-delay="100">
  
          <form method="post">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-4 form-group">
                <label for="name" class="form-label">Name</label>
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required="">
              </div>
              <div class="col-md-4 form-group mt-3 mt-md-0">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required="">
              </div>
              <div class="col-md-4 form-group mt-3 mt-md-0">
                <label for="phone" class="form-label">Phone</label>
                <input type="tel" class="form-control" name="phone" id="phone" placeholder="Your Phone" required="">
              </div>
            </div>
            <div class="row">
              <div class="col-md-4 form-group mt-3">
                <label for="date" class="form-label">Date</label>
                <input type="date" name="date" class="form-control datepicker" id="date" placeholder="Appointment Date" required="">
              </div>
              <div class="col-md-4 form-group mt-3">
                <label for="department" class="form-label">Department</label>
                <select name="department" id="department" class="form-select" required="">
                  <option value="">Select Department</option>
                  <option value="Department 1">Department 1</option>
                  <option value="Department 2">Department 2</option>
                  <option value="Department 3">Department 3</option>
                </select>
              </div>
              <div class="col-md-4 form-group mt-3">
                <label for="doctor" class="form-label">Doctor</label>
                <select name="doctor" id="doctor" class="form-select" required="">
                  <option value="">Select Doctor</option>
                  <option value="Doctor 1">Doctor 1</option>
                  <option value="Doctor 2">Doctor 2</option>
                  <option value="Doctor 3">Doctor 3</option>
                </select>
              </div>
            </div>
  
            <div class="form-group mt-3">
              <label for="message" class="form-label">Message</label>
              <textarea class="form-control" name="message" rows="5" placeholder="Message (Optional)"></textarea>
            </div>
            <div class="mt-3">
              <div class="loading">Loading</div>
              <div class="error-message"></div>
              <div class="sent-message">Your appointment request has been sent successfully. Thank you!</div>
              <div class="text-center"><button type="submit">Make an Appointment</button></div>
            </div>
          </form>
  
        </div>
  
      </section><!-- /Appointment Section -->


{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <title>{% block title %} {% endblock %}</title>
  
  <meta name="description" content="">
  <meta name="keywords" content="">

  <!-- Favicons -->
  <link href="{% static 'static\assets\img\medical.ico' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Fonts -->
  <link href="https://fonts.googleapis.com" rel="preconnect">
  <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/aos/aos.css" rel="stylesheet' %}">
  <link href="{% static 'assets/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Main CSS File -->
  <link href="{% static 'assets/css/main.css' %}" rel="stylesheet">
  <!-- My styles -->
  <link href="{% static 'assets/css/styles.css' %}" rel="stylesheet">

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <!------ Include the above in your HEAD tag ---------->

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">



  <!-- =======================================================
  * Template Name: Medilab
  * Template URL: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/
  * Updated: Aug 07 2024 with Bootstrap v5.3.3
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>



<body class="index-page">

  {% include 'header.html' %}

  <main class="main">
    {% block content %}


    <!-- Contact Section -->
    <section id="contact" class="contact section">

      <!-- Section Title -->
      <div class="container section-title" data-aos="fade-up">
        <h2>Contact</h2>
        <p>Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit</p>
      </div><!-- End Section Title -->

      <div class="mb-5" data-aos="fade-up" data-aos-delay="200">
        <iframe style="border:0; width: 100%; height: 270px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d48389.78314118045!2d-74.006138!3d40.710059!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a22a3bda30d%3A0xb89d1fe6bc499443!2sDowntown%20Conference%20Center!5e0!3m2!1sen!2sus!4v1676961268712!5m2!1sen!2sus" frameborder="0" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div><!-- End Google Maps -->

      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="row gy-4">

          <div class="col-lg-4">
            <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="300">
              <i class="bi bi-geo-alt flex-shrink-0"></i>
              <div>
                <h3>Location</h3>
                <p>A108 Adam Street, New York, NY 535022</p>
              </div>
            </div><!-- End Info Item -->

            <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="400">
              <i class="bi bi-telephone flex-shrink-0"></i>
              <div>
                <h3>Call Us</h3>
                <p>+1 5589 55488 55</p>
              </div>
            </div><!-- End Info Item -->

            <div class="info-item d-flex" data-aos="fade-up" data-aos-delay="500">
              <i class="bi bi-envelope flex-shrink-0"></i>
              <div>
                <h3>Email Us</h3>
                <p>info@example.com</p>
              </div>
            </div><!-- End Info Item -->

          </div>

          <div class="col-lg-8">
            <form action="" method="post" class="php-email-form" data-aos="fade-up" data-aos-delay="200">
              <div class="row gy-4">

                <div class="col-md-6">
                  <input type="text" name="name" class="form-control" placeholder="Your Name" required="">
                </div>

                <div class="col-md-6 ">
                  <input type="email" class="form-control" name="email" placeholder="Your Email" required="">
                </div>

                <div class="col-md-12">
                  <input type="text" class="form-control" name="subject" placeholder="Subject" required="">
                </div>

                <div class="col-md-12">
                  <textarea class="form-control" name="message" rows="6" placeholder="Message" required=""></textarea>
                </div>

                <div class="col-md-12 text-center">
                  <div class="loading">Loading</div>
                  <div class="error-message"></div>
                  <div class="sent-message">Your message has been sent. Thank you!</div>

                  <button type="submit">Send Message</button>
                </div>

              </div>
            </form>
          </div><!-- End Contact Form -->

        </div>

      </div>

    </section><!-- /Contact Section -->

  
    {% endblock %}
  </main>

  {% include 'footer.html' %}

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %} "></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %} "></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %} "></script>
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %} "></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %} "></script>

  <!-- Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


</body>

</html>

templates/header.html
<header id="header" class="header sticky-top">

    <div class="topbar d-flex align-items-center">
      <div class="container d-flex justify-content-center justify-content-md-between">
        <div class="contact-info d-flex align-items-center">
          <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">contact@example.com</a></i>
          <i class="bi bi-phone d-flex align-items-center ms-4"><span>+1 5589 55488 55</span></i>
        </div>
        <div class="social-links d-none d-md-flex align-items-center">
          <a href="{% url 'accounts:register' %}" class="">Register</a>
          <a href="{% url 'accounts:login' %}" class="">Login</a>

        </div>
      </div>
    </div><!-- End Top Bar -->

    <div class="branding d-flex align-items-center">

      <div class="container position-relative d-flex align-items-center justify-content-between">
        <a href="{% url 'medi_app:home' %}" class="logo d-flex align-items-center me-auto">
          <!-- Uncomment the line below if you also wish to use an image logo -->
          <!-- <img src="assets/img/logo.png" alt=""> -->
          <h1 class="sitename">Medilab</h1>
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li><a href="{% url 'medi_app:home' %}" class="active">Home<br></a></li>
            <li><a href="{% url 'medi_app:about' %}">About</a></li>
            <!-- <li><a href="#services">Services</a></li> -->
            <!-- <li><a href="#departments">Departments</a></li> -->
            <!-- <li><a href="#doctors">Doctors</a></li> -->
            <!-- <li class="dropdown"><a href="#"><span>Dropdown</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
              <ul>
                <li><a href="#">Dropdown 1</a></li>
                <li class="dropdown"><a href="#"><span>Deep Dropdown</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                  <ul>
                    <li><a href="#">Deep Dropdown 1</a></li>
                    <li><a href="#">Deep Dropdown 2</a></li>
                    <li><a href="#">Deep Dropdown 3</a></li>
                    <li><a href="#">Deep Dropdown 4</a></li>
                    <li><a href="#">Deep Dropdown 5</a></li>
                  </ul>
                </li>
                <li><a href="#">Dropdown 2</a></li>
                <li><a href="#">Dropdown 3</a></li>
                <li><a href="#">Dropdown 4</a></li>
              </ul>
            </li> -->
            <li><a href="#contact">Contact</a></li>
          </ul>
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

        <a class="cta-btn d-none d-sm-block" href="{% url 'medi_app:appointment' %}">Make an Appointment</a>

      </div>

    </div>

  </header>

templates/pay.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h2>Make a Payment</h2>

<form method="post" action="{% url 'medi_app:stk' %}">
  {% csrf_token %}
    <label class="form-label" for="phone">Phone Number :</label>
    <input type="number" id="phone" name="phone" value="254" placeholder="Phone Number">
    <br><br>

    <label class="form-label" for="amount">Amount :</label>
    <input type="text" id="amount" name="amount" placeholder="Amount">

    <br><br>
  <button type="submit" class="btn btn-success">Submit</button>
</form>


{% endblock %}

templates/show_appointments.html
{% extends 'base.html' %}
{% block title %} Show Appointments {% endblock %}

{% block content %}
<table class="table table-light table-responsive">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Date</th>
            <th>Department</th>
            <th>Doctor</th>
            <th>Message</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for appointment in appointments %}
        <tr>

            <td>{{ appointment.name }}</td>
            <td>{{ appointment.email }}</td>
            <td>{{ appointment.phone }}</td>
            <td>{{ appointment.date }}</td>
            <td>{{ appointment.department }}</td>
            <td>{{ appointment.doctor}}</td>
            <td>{{ appointment.message }}</td>
            <td>
                <a href="{% url 'medi_app:update_appointment' appointment.id %}" class="btn btn-primary">Edit</a>
                <a href="{% url 'medi_app:delete_appointment' appointment.id %}" class="btn btn-danger">Delete</a>
                <a href="{% url 'medi_app:pay' %}" class="btn btn-success">Pay</a>

            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}